### ISSUE TITLE
Remove misrepresenting elements that looks like links and/or navigational parts

### ISSUE THREAD

**Issue by megoth** [Inrupt-inc/solid-react-components#16]
- Remove link-looking span in welcome card, or make it an actual link
- Introduce navigational parts when necessary, or remove their link-looking effects
  - Navbar in top right corner is not necessary yet; if you want to keep it, remove the hover effect
  - Welcome navbar item in top left corner is not necessary yet; introduce it when we have multiple pages (or at least remove the hover-effect that makes it look like a link)
  - Can probably remove link in logo also for now, until we have more pages available

I know there are actually multiple pages in the application, but the pages available given any state makes it unnecessary to have navbars. They will be shortly introduced, so might ignore this issue for now, but in general we don't want to introduce layout and navigational patterns before they are needed.

**Comment by james-martin-jd** [comment]
I believe these issues are all resolved now in the 0.2.1 release?

**Comment by megoth** [comment]
Yes, all issues are adressed ^_^

I'll close this issue.
