### ISSUE TITLE
Errors during building the `demo` app. 

### ISSUE THREAD

**Issue by aorumbayev** [Inrupt-inc/solid-react-components#35]
I was trying to build a demo app when the following issue appeared. Am I using wrong package manager or a node version?

### How to reproduce
1. Clone the repository
2. Run `yarn install`
3. Run `yarn run demo`
4. See the following error : 

```bash
Creating a build of the demo app...
Failed to compile.

chunk main [entry]
index.js
Missing external configuration for type:commonjs2


error Command failed with exit code 1.
```

### Version information
- Node Version: `v10.14.2`
- yarn Version: `1.13.0`
- npm Version: `6.4.1`
- OS: `macOS v10.14.3` 
- Browser: `Chrome`
- Browser Version: `v72.0.3626.119`

**Comment by james-martin-jd** [comment]
This issue should be fixed in the upcoming 0.3.0 release. There was a missing declaration in the webpack config specifically for the demo build.

If you'd like to try it sooner, our release candidate is available for testing, version 0.3.0-rc.0 is now published.

**Comment by aorumbayev** [comment]
@james-martin-jd thank you, I'll give it a try on release candidate 👍

**Comment by james-martin-jd** [comment]
Version 0.3.0 is release, which fixes this issue
